# Site settings
title: Razmova
description: Free Private AI Language Practice & On-Device Chat
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://razmova.ca" # the base hostname & protocol for your site

# Theme
# (custom layout in _layouts/default.html)

# Site author
author:
  name: Tatiana Tarnovskaya

# SEO settings
lang: en-US
plugins:
  - jekyll-seo-tag

# Additional SEO content 
tagline: "Free Private AI Language Practice & On-Device Chat"
keywords: "free offline ai, private language practice, on device ai ios, local llm chat, learn languages securely, speak confidently app ios, no internet ai chat, language learning app, secure ai conversation, offline language practice"

# GitHub Pages settings
github:
  repository_name: razmova-ai
  repository_url: https://github.com/Tatiana2020/razmova-ai
  is_project_page: false
